name: Add Comment
on:
    pull_request:
        types:
            - closed
        branches:
            - development
jobs:
    add_comment:

        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: checkout
              uses: "actions/checkout@v2"            
            - name: add_comment
              if: ${{github.event.pull_request.merged}}
              run: |
                gh pr view ${{github.event.number}} --json body --jq .body > /tmp/commentBody
                echo "PR: ${{github.event.pull_request.html_url}} Author: ${{github.event.pull_request.user.login}}" >> /tmp/commentBody
                mainIssueNumber=$(gh pr create -B staging -H test-pr-template -d --title "Main" --body "" 2>&1 | grep "github.com" | awk '{split($0, a, "/"); print a[length(a)]}')
                gh pr comment $mainIssueNumber --body-file /tmp/commentBody            
