name: Add Comment
on:
    pull_request:
        types:
            - opened
        branches:
            - development
jobs:
    add_comment:
    runs-on: ubuntu-latest
    steps:
        - run: |
            gh pr view ${{github.event.number}} --json body --jq .body > /tmp/commentBody
            mainIssueNumber=$(gh pr create -B main -H test-pr-template -d --title "Main" --body "" 2>&1 | grep "github.com" | awk '{split($0, a, "/"); print a[length(a)]}')
            gh pr comment $mainIssueNumber --body-file /tmp/commentBody            
